[workspace]
resolver = "3"
members = [
    "engine/Trident",
    "engine/WgpuRenderer/rust",
    "mserver/Archive",
    "mserver/CLI",
    "mserver/Client",
    "mserver/MasterService",
]

[profile.dbg]
inherits = "dev"

[profile.rwdi]
inherits = "release"
debug = true

[profile.rel]
inherits = "release"
